tags = ["home", "www", "msg", "dev", "mus", "gfx", "pac", "kee"]
disable_current_tag_swap = true 
workspaces = [
    { y = 0, x = 0, height = 1080, width = 1920, id = 0 },
    { y = 0, x = 1920, height = 1080, width = 1920, id = 1 },
]
layout_mode = "Workspace"
layouts = [
    "MainAndVertStack",
    "GridHorizontal",
    "EvenHorizontal",
    "EvenVertical",
    "Fibonacci",
    "LeftMain",
    "CenterMainBalanced",
    "Monocle",
    "RightWiderLeftStack",
    "LeftWiderRightStack",
]

scratchpad = [
    { name = "Alacritty", value = "alacritty -e 'nvim' '/home/nikoof/.notes'", x = 760, y = 390, height = 300, width = 400 },
]
window_rules = [
    { window_class = "firefox",   spawn_on_tag = 2 },
    { window_class = "discord",   spawn_on_tag = 3 },
    { window_class = "spotify",   spawn_on_tag = 5 },
    { window_class = "Steam",     spawn_on_tag = 7 },
]

insert_behavior = "Bottom"
disable_tile_drag = false 
disable_window_snap = true
focus_behaviour = "Sloppy"
focus_new_windows = true

modkey = "Mod4"
mousekey = "Mod4"
keybind = [
    { command = "Execute",           value = "dmenu_run", modifier = "modkey", key = "r" },
    { command = "Execute",           value = "alacritty", modifier = "modkey", key = "Return" },
    { command = "Execute",           value = "firefox",   modifier = "modkey", key = "b" },

    { command = "Execute",           value = "scrot  -e 'xclip -selection clipboard -t image/png -i $f && rm -rf $f'", key = "Print" },
    { command = "Execute",           value = "scrot -ue 'xclip -selection clipboard -t image/png -i $f && rm -rf $f'", modifier = "Alt", key = "Print" },
    { command = "Execute",           value = "sleep 0.2; scrot -s -f -e 'xclip -selection clipboard -t image/png -i $f && rm -rf $f'", modifier = ["modkey", "Shift"], key = "s" },

    { command = "Execute",           value = "pactl set-sink-volume $(pactl get-default-sink)  +5%", key = "XF86XK_AudioRaiseVolume" },
    { command = "Execute",           value = "pactl set-sink-volume $(pactl get-default-sink)  -5%", key = "XF86XK_AudioLowerVolume" },
    { command = "Execute",           value = "pactl set-sink-mute $(pactl get-default-sink) toggle", key = "XF86XK_AudioLowerVolume" },

    { command = "Execute",           value = "playerctl play-pause", key = "XF86XK_AudioPlay" },
    { command = "Execute",           value = "playerctl stop",       key = "XF86XK_AudioStop" },
    { command = "Execute",           value = "playerctl previous",   key = "XF86XK_AudioPrev" },
    { command = "Execute",           value = "playerctl next",       key = "XF86XK_AudioNext" },

    { command = "CloseWindow",       value = "",          modifier = "modkey", key = "w" },
    { command = "ToggleFloating",    value = "",          modifier = "modkey", key = "f" }, 
    { command = "ToggleSticky",      value = "",          modifier = "modkey", key = "s" },
    { command = "FocusWindowUp",     value = "",          modifier = "modkey", key = "k" },
    { command = "FocusWindowDown",   value = "",          modifier = "modkey", key = "j" },
    { command = "ToggleScratchPad",  value = "Alacritty", modifier = "modkey", key = "p" },
    { command = "ToggleFullScreen",  value = "",          modifier = ["modkey", "Shift"], key = "f" },
    { command = "MoveWindowUp",      value = "",          modifier = ["modkey", "Shift"], key = "k" },
    { command = "MoveWindowDown",    value = "",          modifier = ["modkey", "Shift"], key = "j" },

    { command = "NextLayout",        value = "",          modifier = "modkey", key = "apostrophe" },
    { command = "PreviousLayout",    value = "",          modifier = "modkey", key = "semicolon" },
    { command = "IncreaseMainWidth", value = "5",         modifier = "modkey", key = "l" },
    { command = "DecreaseMainWidth", value = "5",         modifier = "modkey", key = "h" },

    { command = "SetLayout",         value = "Monocle",          modifier = "modkey", key = "m" },
    { command = "SetLayout",         value = "MainAndVertStack", modifier = "modkey", key = "t" },

    { command = "FocusWorkspaceNext",                   modifier = "modkey", key = "period" },
    { command = "FocusWorkspacePrevious",               modifier = "modkey", key = "comma" },
    
    { command = "GotoTag",           value = "1",         modifier = "modkey", key = "1" },
    { command = "GotoTag",           value = "2",         modifier = "modkey", key = "2" },
    { command = "GotoTag",           value = "3",         modifier = "modkey", key = "3" },
    { command = "GotoTag",           value = "4",         modifier = "modkey", key = "4" },
    { command = "GotoTag",           value = "5",         modifier = "modkey", key = "5" },
    { command = "GotoTag",           value = "6",         modifier = "modkey", key = "6" },
    { command = "GotoTag",           value = "7",         modifier = "modkey", key = "7" },
    { command = "GotoTag",           value = "8",         modifier = "modkey", key = "8" },
    { command = "GotoTag",           value = "9",         modifier = "modkey", key = "9" },

    { command = "MoveToTag",         value = "1",         modifier = ["modkey", "Shift"], key = "1" },
    { command = "MoveToTag",         value = "2",         modifier = ["modkey", "Shift"], key = "2" },
    { command = "MoveToTag",         value = "3",         modifier = ["modkey", "Shift"], key = "3" },
    { command = "MoveToTag",         value = "4",         modifier = ["modkey", "Shift"], key = "4" },
    { command = "MoveToTag",         value = "5",         modifier = ["modkey", "Shift"], key = "5" },
    { command = "MoveToTag",         value = "6",         modifier = ["modkey", "Shift"], key = "6" },
    { command = "MoveToTag",         value = "7",         modifier = ["modkey", "Shift"], key = "7" },
    { command = "MoveToTag",         value = "8",         modifier = ["modkey", "Shift"], key = "8" },
    { command = "MoveToTag",         value = "9",         modifier = ["modkey", "Shift"], key = "9" },
    
    { command = "SoftReload",      value = "",          modifier = ["modkey", "Shift"], key = "r" },
    { command = "HardReload",      value = "",          modifier = ["modkey", "Shift", "Control"], key = "r" },
    { command = "Execute",         value = "loginctl kill-session $XDG_SESSION_ID", modifier = ["modkey", "Shift"], key = "q" },
]
